server:
  port: 7906
spring:
  application:
    name: service-movie-feign-with-hystrix
eureka:
  client:
    serviceUrl:
      defaultZone: http://user:123456@localhost:8761/eureka/
    healthcheck:
      enabled: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}

feign:
  hystrix:
    enabled: true    # this must be enabled