server:
  port: 8761
spring:
  security:
    user:
      name: user
      password: 123456
  application:
    name: eureka-server        
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://user:123456@localhost:8761/eureka/