spring:
  application:
    name: EUREKA-HA
eureka:
  client:
    serviceUrl:
      defaultZone: http://user:123456@localhost:8801/eureka/,http://user:123456@localhost:8802/eureka/,http://user:123456@localhost:8803/eureka/

---
spring:
  profiles: peer1
  security:
    user:
      name: user
      password: 123456  
server:
  port: 8801  
eureka:
  instance:
    hostname: localhost

---
spring:
  profiles: peer2
  security:
    user:
      name: user
      password: 123456  
server:
  port: 8802  
eureka:
  instance:
    hostname: localhost

---
spring:
  profiles: peer3
  security:
    user:
      name: user
      password: 123456  
server:
  port: 8803  
eureka:
  instance:
    hostname: localhost      